### PR TITLE
doc: add `char` to the list of primitive types

### PR DESCRIPTION
**Pull request by bennn**

### CODE REVIEW

**Comment by bennn** [comment]
I tried to sign the CLA
https://code.facebook.com/cla/individual

It sent me to a page that says something went wrong, go back
https://code.facebook.com/github/callback?code=367744e098814278fd84&state=AVFYy7b9bzMjFpctyFGasmOdKhQxhNLn6BWOaD07oQWNEuFQh-rg1uUO4QhxJRibi_LTjXpoHzgJZwYPoi_CBC2UlX6Q-xxdLh4ayA49u1dV2DoglvSl38Nyvd_rdzXQFasuwe5ftJfDqfi8ln1A89go_K-Ye257YocvdjLOSFmqWmW5Bl0EQ_CiUk1KMJbkapWl4q0H2yq4D0KM_T9bgO1wBxcj3nFkIsQ36gTTVbbId7RAkcjXJH0Gg5mxL8Vj-2-RXLk7qUToPc1UsjagSrA9

So here's my info:
```
GitHub Username:
bennn

Name:
Ben Greenman

Email:
benjaminlgreenman@gmail.com

Country:
United States

I agree to the Facebook, Inc. Individual Contributor License Agreement ("Agreement"), v1.0
```

<details>
Facebook, Inc. Individual Contributor License Agreement ("Agreement"), v1.0

You accept and agree to the following terms and conditions for Your present and future Contributions submitted to Facebook, Inc. ("Facebook"). Except for the license granted herein to Facebook and recipients of software distributed by Facebook, You reserve all right, title, and interest in and to Your Contributions.

1. Definitions.

"You" (or "Your") shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement with Facebook. For legal entities, the entity making a Contribution and all other entities that control, are controlled by, or are under common control with that entity are considered to be a single Contributor. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.

"Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is intentionally submitted by You to Facebook for inclusion in, or documentation of, any of the products owned or managed by Facebook (the "Work"). For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to Facebook or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, Facebook for the purpose of discussing and improving the Work, but excluding communication that is conspicuously marked or otherwise designated in writing by You as "Not a Contribution."

2. Grant of Copyright License. Subject to the terms and conditions of this Agreement, You hereby grant to Facebook and to recipients of software distributed by Facebook a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.

3. Grant of Patent License. Subject to the terms and conditions of this Agreement, You hereby grant to Facebook and to recipients of software distributed by Facebook a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by You that are necessarily infringed by Your Contribution(s) alone or by combination of Your Contribution(s) with the Work to which such Contribution(s) was submitted. If any entity institutes patent litigation against You or any other entity (including a cross-claim or counterclaim in a lawsuit) alleging that your Contribution, or the Work to which you have contributed, constitutes direct or contributory patent infringement, then any patent licenses granted to that entity under this Agreement for that Contribution or Work shall terminate as of the date such litigation is filed.

4. You represent that you are legally entitled to grant the above license. If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer, that your employer has waived such rights for your Contributions to Facebook, or that your employer has executed a separate Corporate CLA with Facebook.

5. You represent that each of Your Contributions is Your original creation (see section 7 for submissions on behalf of others). You represent that Your Contribution submissions include complete details of any third-party license or other restriction (including, but not limited to, related patents and trademarks) of which you are personally aware and which are associated with any part of Your Contributions.

6. You are not expected to provide support for Your Contributions, except to the extent You desire to provide support. You may provide support for free, for a fee, or not at all. Unless required by applicable law or agreed to in writing, You provide Your Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON- INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.
</details>

**Comment by carljm** [comment]
Hi @bennn , sorry about the trouble with CLA signing. Not sure what's up there, I've sent a request over to the OSS Tools team to have them take a look and hopefully get you all set so we can merge these.

**Comment by carljm** [comment]
@bennn I'm told this issue should now be fixed and you should be able to follow the link to submit the CLA. Sorry to make you repeat it!

**Comment by bennn** [comment]
Hmm, it still doesn't work --- neither on brave nor chrome. I guess I'll try again tomorrow.

I did give FB access to my GitHub account.

**Comment by carljm** [comment]
Ugh, sorry, following up again...

**Comment by carljm** [comment]
Ok, checked back and was told that the initial fix wasn't complete; a fuller fix should be deployed within a few hours. So hopefully by tomorrow will be actually resolved.

**Comment by jurajh-fb** [comment]
Hi @bennn,
The fix deployed last night. You should be good to go, but let me know if you run into any other issues. Apologies for the delay and thanks for being patient!

**Comment by bennn** [comment]
Yes! I was able to submit a CLA. Thanks Carl and @jurajh-fb !

**Comment by tekknolagi** [comment]
Thanks!

**Pull request merged**
